### ISSUE TITLE
Auto-Silence-Cut.py missing from the repo

### ISSUE THREAD

**Issue by randyrektor** [YourAverageMo/auto-silence-cut#1]
Hey there,

This project looks awesome. I am just in the process of installing the dependancies, but Auto-Silence-Cut.py seems to be missing from the repo.

Thanks in advance!

**Comment by YourAverageMo** [comment]
Hey randy!

Thanks for checking out my project and im glad you like it. Good catch its actually just a naming issue, its currently named 'auto-editor.py' in the repo but i will change it to 'auto-silence-cut.py' in the next commit to better match the readme.md

let me know if there's anything else you catch or something cool you'd like me to add! Oh, actually on that note. i think in the most recent DR 19.1 update they revoted graphical user interfaces from 3rd party scripts UNLESS you paid for studio... havnt been able to check it out myself but just a heads up if your on the most recent update the GUI may not work.

**Comment by YourAverageMo** [comment]
are you on mac? the 'AttributeError: module 'subprocess' has no attribute 'CREATE_NO_WINDOW'' suggests your on mac. i havnt been able to test it on mac but thought it would have no issues.

**Comment by randyrektor** [comment]
Ahhh yes I am on a Mac. Sorry, I'm new to this stuff haha. I'll see if I can find a nice workaround. Thanks for the quick replies!

**Comment by YourAverageMo** [comment]
had a feeling no problem. ive been meaning to test it on mac anyways, ill give it a look tonight and see what i can do. till then closing this issue and making a new one

**Comment by randyrektor** [comment]
Thanks so much! I really appreciate it
